export const worldCurrencies = [
  { label: "United States dollar (USD)", value: "USD", decimals: 2 },
  { label: "Canadian dollar (CAD)", value: "CAD", decimals: 2 },
  { label: "European Euro (EUR)", value: "EUR", decimals: 2 },
  { label: "British pound (GBP)", value: "GBP", decimals: 2 },
  { label: "Australian dollar (AUD)", value: "AUD", decimals: 2 },
  { label: "Hong Kong dollar (HKD)", value: "HKD", decimals: 2 },
  { label: "Singapore dollar (SGD)", value: "SGD", decimals: 2 },
  { label: "Japanese yen (JPY)", value: "JPY", decimals: 0 },
  { label: "Swiss franc (CHF)", value: "CHF", decimals: 2 },
  { label: "Chinese/Yuan renminbi (CNY)", value: "CNY", decimals: 2 },
  { label: "South Korean won (KRW)", value: "KRW", decimals: 0 },
  { label: "Indian rupee (INR)", value: "INR", decimals: 2 },
  { label: "Brazilian real (BRL)", value: "BRL", decimals: 2 },
  { label: "Russian ruble (RUB)", value: "RUB", decimals: 2 },
  { label: "South African rand (ZAR)", value: "ZAR", decimals: 2 },
  { label: "New Zealand dollar (NZD)", value: "NZD", decimals: 2 },
  { label: "Norwegian krone (NOK)", value: "NOK", decimals: 2 },
  { label: "Swedish krona (SEK)", value: "SEK", decimals: 2 },
  { label: "Danish krone (DKK)", value: "DKK", decimals: 2 },
  { label: "Polish zloty (PLN)", value: "PLN", decimals: 2 },
  { label: "Turkish lira (TRY)", value: "TRY", decimals: 2 },
  { label: "Israeli new sheqel (ILS)", value: "ILS", decimals: 2 },
  { label: "Mexican peso (MXN)", value: "MXN", decimals: 2 },
  { label: "New Taiwan dollar (TWD)", value: "TWD", decimals: 2 },
  { label: "Argentine peso (ARS)", value: "ARS", decimals: 2 },

  { label: "Afghan afghani (AFN)", value: "AFN", decimals: 2 },
  { label: "Albanian lek (ALL)", value: "ALL", decimals: 2 },
  { label: "Algerian dinar (DZD)", value: "DZD", decimals: 2 },
  { label: "Angolan kwanza (AOA)", value: "AOA", decimals: 2 },
  { label: "Armenian dram (AMD)", value: "AMD", decimals: 2 },
  { label: "Aruban florin (AWG)", value: "AWG", decimals: 2 },
  { label: "Azerbaijani manat (AZN)", value: "AZN", decimals: 2 },
  { label: "Bahamian dollar (BSD)", value: "BSD", decimals: 2 },
  { label: "Bahraini dinar (BHD)", value: "BHD", decimals: 3 },
  { label: "Bangladeshi taka (BDT)", value: "BDT", decimals: 2 },
  { label: "Barbadian dollar (BBD)", value: "BBD", decimals: 2 },
  { label: "Belarusian ruble (BYR)", value: "BYR", decimals: 0 },
  { label: "Belarusian ruble (BYN)", value: "BYN", decimals: 2 },
  { label: "Belize dollar (BZD)", value: "BZD", decimals: 2 },
  { label: "Bermudian dollar (BMD)", value: "BMD", decimals: 2 },
  { label: "Bhutanese ngultrum (BTN)", value: "BTN", decimals: 2 },
  { label: "Bolivian boliviano (BOB)", value: "BOB", decimals: 2 },
  {
    label: "Bosnia and Herzegovina konvertibilna marka (BAM)",
    value: "BAM",
    decimals: 2,
  },
  { label: "Botswana pula (BWP)", value: "BWP", decimals: 2 },
  { label: "Brunei dollar (BND)", value: "BND", decimals: 2 },
  { label: "Bulgarian lev (BGN)", value: "BGN", decimals: 2 },
  { label: "Burundi franc (BIF)", value: "BIF", decimals: 0 },
  { label: "Cambodian riel (KHR)", value: "KHR", decimals: 2 },
  { label: "Cape Verdean escudo (CVE)", value: "CVE", decimals: 2 },
  { label: "Cayman Islands dollar (KYD)", value: "KYD", decimals: 2 },
  { label: "Central African CFA franc (GQE)", value: "GQE", decimals: 0 },
  { label: "Central African CFA franc (XAF)", value: "XAF", decimals: 0 },
  { label: "CFP franc (XPF)", value: "XPF", decimals: 0 },
  { label: "Chilean peso (CLP)", value: "CLP", decimals: 0 },
  { label: "Colombian peso (COP)", value: "COP", decimals: 2 },
  { label: "Comorian franc (KMF)", value: "KMF", decimals: 0 },
  { label: "Congolese franc (CDF)", value: "CDF", decimals: 2 },
  { label: "Costa Rican colon (CRC)", value: "CRC", decimals: 2 },
  { label: "Croatian kuna (HRK)", value: "HRK", decimals: 2 },
  { label: "Cuban peso (CUC)", value: "CUC", decimals: 2 },
  { label: "Czech koruna (CZK)", value: "CZK", decimals: 2 },
  { label: "Djiboutian franc (DJF)", value: "DJF", decimals: 0 },
  { label: "Dominican peso (DOP)", value: "DOP", decimals: 2 },
  { label: "East Caribbean dollar (XCD)", value: "XCD", decimals: 2 },
  { label: "Egyptian pound (EGP)", value: "EGP", decimals: 2 },
  { label: "Eritrean nakfa (ERN)", value: "ERN", decimals: 2 },
  { label: "Estonian kroon (EEK)", value: "EEK", decimals: 2 },
  { label: "Ethiopian birr (ETB)", value: "ETB", decimals: 2 },
  { label: "Falkland Islands pound (FKP)", value: "FKP", decimals: 2 },
  { label: "Fijian dollar (FJD)", value: "FJD", decimals: 2 },
  { label: "Gambian dalasi (GMD)", value: "GMD", decimals: 2 },
  { label: "Georgian lari (GEL)", value: "GEL", decimals: 2 },
  { label: "Ghanaian cedi (GHS)", value: "GHS", decimals: 2 },
  { label: "Gibraltar pound (GIP)", value: "GIP", decimals: 2 },
  { label: "Guatemalan quetzal (GTQ)", value: "GTQ", decimals: 2 },
  { label: "Guinean franc (GNF)", value: "GNF", decimals: 0 },
  { label: "Guyanese dollar (GYD)", value: "GYD", decimals: 2 },
  { label: "Haitian gourde (HTG)", value: "HTG", decimals: 2 },
  { label: "Honduran lempira (HNL)", value: "HNL", decimals: 2 },
  { label: "Hungarian forint (HUF)", value: "HUF", decimals: 0 },
  { label: "Icelandic króna (ISK)", value: "ISK", decimals: 0 },
  { label: "Indonesian rupiah (IDR)", value: "IDR", decimals: 2 },
  { label: "Iranian rial (IRR)", value: "IRR", decimals: 2 },
  { label: "Iraqi dinar (IQD)", value: "IQD", decimals: 3 },
  { label: "Jamaican dollar (JMD)", value: "JMD", decimals: 2 },
  { label: "Jordanian dinar (JOD)", value: "JOD", decimals: 3 },
  { label: "Kazakhstani tenge (KZT)", value: "KZT", decimals: 2 },
  { label: "Kenyan shilling (KES)", value: "KES", decimals: 2 },
  { label: "Kuwaiti dinar (KWD)", value: "KWD", decimals: 3 },
  { label: "Kyrgyzstani som (KGS)", value: "KGS", decimals: 2 },
  { label: "Lao kip (LAK)", value: "LAK", decimals: 2 },
  { label: "Latvian lats (LVL)", value: "LVL", decimals: 2 },
  { label: "Lebanese lira (LBP)", value: "LBP", decimals: 2 },
  { label: "Lesotho loti (LSL)", value: "LSL", decimals: 2 },
  { label: "Liberian dollar (LRD)", value: "LRD", decimals: 2 },
  { label: "Libyan dinar (LYD)", value: "LYD", decimals: 3 },
  { label: "Lithuanian litas (LTL)", value: "LTL", decimals: 2 },
  { label: "Macanese pataca (MOP)", value: "MOP", decimals: 2 },
  { label: "Macedonian denar (MKD)", value: "MKD", decimals: 2 },
  { label: "Malagasy ariary (MGA)", value: "MGA", decimals: 0 },
  { label: "Malawian kwacha (MWK)", value: "MWK", decimals: 2 },
  { label: "Malaysian ringgit (MYR)", value: "MYR", decimals: 2 },
  { label: "Maldivian rufiyaa (MVR)", value: "MVR", decimals: 2 },
  { label: "Mauritanian ouguiya (MRO)", value: "MRO", decimals: 0 },
  { label: "Mauritian rupee (MUR)", value: "MUR", decimals: 2 },
  { label: "Moldovan leu (MDL)", value: "MDL", decimals: 2 },
  { label: "Mongolian tugrik (MNT)", value: "MNT", decimals: 2 },
  { label: "Moroccan dirham (MAD)", value: "MAD", decimals: 2 },
  { label: "Mozambican metical (MZM)", value: "MZM", decimals: 2 },
  { label: "Myanma kyat (MMK)", value: "MMK", decimals: 2 },
  { label: "Namibian dollar (NAD)", value: "NAD", decimals: 2 },
  { label: "Nepalese rupee (NPR)", value: "NPR", decimals: 2 },
  { label: "Netherlands Antillean gulden (ANG)", value: "ANG", decimals: 2 },
  { label: "Nicaraguan córdoba (NIO)", value: "NIO", decimals: 2 },
  { label: "Nigerian naira (NGN)", value: "NGN", decimals: 2 },
  { label: "North Korean won (KPW)", value: "KPW", decimals: 0 },
  { label: "Omani rial (OMR)", value: "OMR", decimals: 3 },
  { label: "Pakistani rupee (PKR)", value: "PKR", decimals: 2 },
  { label: "Panamanian balboa (PAB)", value: "PAB", decimals: 2 },
  { label: "Papua New Guinean kina (PGK)", value: "PGK", decimals: 2 },
  { label: "Paraguayan guarani (PYG)", value: "PYG", decimals: 0 },
  { label: "Peruvian nuevo sol (PEN)", value: "PEN", decimals: 2 },
  { label: "Philippine peso (PHP)", value: "PHP", decimals: 2 },
  { label: "Qatari riyal (QAR)", value: "QAR", decimals: 2 },
  { label: "Romanian leu (RON)", value: "RON", decimals: 2 },
  { label: "Saint Helena pound (SHP)", value: "SHP", decimals: 2 },
  { label: "Samoan tala (WST)", value: "WST", decimals: 2 },
  { label: "Saudi riyal (SAR)", value: "SAR", decimals: 2 },
  { label: "Serbian dinar (RSD)", value: "RSD", decimals: 2 },
  { label: "Seychellois rupee (SCR)", value: "SCR", decimals: 2 },
  { label: "Sierra Leonean leone (SLL)", value: "SLL", decimals: 2 },
  { label: "Solomon Islands dollar (SBD)", value: "SBD", decimals: 2 },
  { label: "Somali shilling (SOS)", value: "SOS", decimals: 2 },
  { label: "Special Drawing Rights (XDR)", value: "XDR", decimals: 2 },
  { label: "Sri Lankan rupee (LKR)", value: "LKR", decimals: 2 },
  { label: "Sudanese pound (SDG)", value: "SDG", decimals: 2 },
  { label: "Surinamese dollar (SRD)", value: "SRD", decimals: 2 },
  { label: "Swazi lilangeni (SZL)", value: "SZL", decimals: 2 },
  { label: "Syrian pound (SYP)", value: "SYP", decimals: 2 },
  { label: "Tajikistani somoni (TJS)", value: "TJS", decimals: 2 },
  { label: "Tanzanian shilling (TZS)", value: "TZS", decimals: 2 },
  { label: "Thai baht (THB)", value: "THB", decimals: 2 },
  { label: "Trinidad and Tobago dollar (TTD)", value: "TTD", decimals: 2 },
  { label: "Tunisian dinar (TND)", value: "TND", decimals: 3 },
  { label: "Turkmen manat (TMT)", value: "TMT", decimals: 2 },
  { label: "UAE dirham (AED)", value: "AED", decimals: 2 },
  { label: "Ugandan shilling (UGX)", value: "UGX", decimals: 0 },
  { label: "Ukrainian hryvnia (UAH)", value: "UAH", decimals: 2 },
  { label: "Uruguayan peso (UYU)", value: "UYU", decimals: 2 },
  { label: "Uzbekistani som (UZS)", value: "UZS", decimals: 2 },
  { label: "Vanuatu vatu (VUV)", value: "VUV", decimals: 0 },
  { label: "Venezuelan bolivar (VEB)", value: "VEB", decimals: 2 },
  { label: "Vietnamese dong (VND)", value: "VND", decimals: 0 },
  { label: "West African CFA franc (XOF)", value: "XOF", decimals: 0 },
  { label: "Yemeni rial (YER)", value: "YER", decimals: 2 },
  { label: "Zambian kwacha (ZMK)", value: "ZMK", decimals: 2 },
  { label: "Zimbabwean dollar (ZWR)", value: "ZWR", decimals: 2 },
];
