-- ============================================================================
-- Consolidated data-model refactor migration.
--
-- This single migration folds in incremental migrations from the phase
-- branches: create_lots_table, add_alt_value_to_valuation,
-- lots_cascade_on_activity_delete, add_account_id_to_assets,
-- clear_positions_json, clear_calculated_positions_json, and
-- create_snapshot_positions.
--
-- Schema only. All data backfills (lots from activities, snapshot_positions
-- from holdings_snapshots.positions JSON) are performed by application code
-- on first startup after this migration runs. Running the backfill in code
-- lets it be interruptable, per-account, and resumable. TOTAL portfolio
-- rows in daily_account_valuation are regenerated by the new aggregator on
-- the next portfolio recalc; no migration-time backfill is needed.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. lots — materialized tax lots (the new authoritative source of positions)
-- ----------------------------------------------------------------------------

CREATE TABLE lots (
    -- Identity & foreign keys
    id                  TEXT    PRIMARY KEY NOT NULL,
    account_id          TEXT    NOT NULL,
    asset_id            TEXT    NOT NULL,

    -- Open state — who opened the lot, when, and at what basis.
    -- open_activity_id is NULL for lots created from HOLDINGS-mode snapshots.
    open_date           TEXT    NOT NULL,
    open_activity_id    TEXT,
    original_quantity   TEXT    NOT NULL,
    cost_per_unit       TEXT    NOT NULL,
    -- Immutable: the cost basis at lot creation (cost_per_unit × original_quantity
    -- + fee_allocated, in cost_basis_currency).
    original_cost_basis TEXT    NOT NULL,
    -- Mutable: the open cost basis remaining for partial-sell tracking. Reduced
    -- proportionally as remaining_quantity is consumed.
    remaining_cost_basis TEXT   NOT NULL,
    fee_allocated       TEXT    NOT NULL DEFAULT '0',

    -- Current state — populated over the life of the lot.
    remaining_quantity  TEXT    NOT NULL,
    -- Cumulative product of post-acquisition SPLIT ratios for the lot's
    -- asset. Default '1' means no splits since the lot was opened. Lot
    -- columns above (original_quantity, cost_per_unit, original_cost_basis,
    -- fee_allocated, remaining_quantity) are stored in as-acquired
    -- (pre-split) units; effective shares held now = remaining_quantity *
    -- split_ratio. Total cost basis is split-invariant.
    split_ratio         TEXT    NOT NULL DEFAULT '1',
    is_closed           INTEGER NOT NULL DEFAULT 0,

    -- Close state — populated when the lot is fully disposed.
    close_date          TEXT,
    close_activity_id   TEXT,

    -- Audit
    created_at          TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at          TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),

    CHECK (is_closed    IN (0, 1)),

    -- Tax conclusions (disposal_method, is_wash_sale, holding_period) live in
    -- separate tax-overlay tables in a later phase. The neutral lots table
    -- intentionally stores only inventory facts.

    -- open_activity_id is CASCADE (not SET NULL) — deleting the opening
    -- activity removes the lot rather than orphaning it with a NULL ref.
    FOREIGN KEY (account_id)        REFERENCES accounts(id)    ON DELETE CASCADE,
    FOREIGN KEY (asset_id)          REFERENCES assets(id)      ON DELETE CASCADE,
    FOREIGN KEY (open_activity_id)  REFERENCES activities(id)  ON DELETE CASCADE,
    FOREIGN KEY (close_activity_id) REFERENCES activities(id)  ON DELETE SET NULL
);

-- Hot-path query: valuation = lots JOIN quotes WHERE is_closed = 0
CREATE INDEX idx_lots_account_asset ON lots(account_id, asset_id);
-- Query open lots for an asset across all accounts
CREATE INDEX idx_lots_asset_open    ON lots(asset_id, is_closed, open_date);
-- Query all open lots for an account
CREATE INDEX idx_lots_account_open  ON lots(account_id, is_closed);
-- Reverse-lookup: which lot was opened by this activity?
CREATE INDEX idx_lots_open_activity ON lots(open_activity_id)
    WHERE open_activity_id IS NOT NULL;


-- ----------------------------------------------------------------------------
-- 2. daily_account_valuation — add alternative_market_value column
-- ----------------------------------------------------------------------------
-- Lets the Investments page filter out precious metals / property
-- consistently in both header and account cards.

ALTER TABLE daily_account_valuation
    ADD COLUMN alternative_market_value TEXT NOT NULL DEFAULT '0';


-- ----------------------------------------------------------------------------
-- 3. holdings_snapshots — drop stale merged-TOTAL rows
-- ----------------------------------------------------------------------------
-- The merged-TOTAL-snapshot pipeline is removed. TOTAL holdings are now
-- synthesized on demand: positions from lots, cash from per-account
-- snapshot aggregation. Pre-upgrade installs may have accumulated TOTAL
-- rows from the old pipeline; they have no readers or writers anymore.

DELETE FROM holdings_snapshots WHERE account_id = 'TOTAL';


-- ----------------------------------------------------------------------------
-- 4. snapshot_positions — relational positions for HOLDINGS-mode accounts
-- ----------------------------------------------------------------------------
-- Replaces the positions JSON blob in holdings_snapshots. Integer
-- autoincrement PK; natural key is (snapshot_id, asset_id). Application
-- code populates this on first startup from the legacy positions JSON
-- for HOLDINGS-mode snapshots, and clears the JSON incrementally as
-- each account is migrated so a crash resumes cleanly.

CREATE TABLE snapshot_positions (
    -- Identity & foreign keys
    id                   INTEGER PRIMARY KEY AUTOINCREMENT,
    snapshot_id          TEXT    NOT NULL REFERENCES holdings_snapshots(id) ON DELETE CASCADE,
    asset_id             TEXT    NOT NULL REFERENCES assets(id)              ON DELETE CASCADE,

    -- Position state
    quantity             TEXT    NOT NULL,
    average_cost         TEXT    NOT NULL,
    total_cost_basis     TEXT    NOT NULL,
    currency             TEXT    NOT NULL,
    contract_multiplier  TEXT    NOT NULL DEFAULT '1',

    -- Metadata
    inception_date       TEXT    NOT NULL,
    is_alternative       INTEGER NOT NULL DEFAULT 0,

    -- Audit
    created_at           TEXT    NOT NULL,
    last_updated         TEXT    NOT NULL,

    UNIQUE (snapshot_id, asset_id)
);

CREATE INDEX idx_snapshot_positions_snapshot_id ON snapshot_positions(snapshot_id);
CREATE INDEX idx_snapshot_positions_asset_id    ON snapshot_positions(asset_id);

-- Backfill snapshot_positions from existing positions JSON. HOLDINGS-mode
-- snapshots (MANUAL_ENTRY, BROKER_IMPORTED, CSV_IMPORT, SYNTHETIC) carry
-- their position data in the JSON blob on today's schema; the new read
-- path sources from snapshot_positions, so existing rows must be copied
-- over for HOLDINGS accounts to keep working after upgrade. One-shot
-- atomic INSERT — no resume logic needed.
--
-- json_extract on numeric fields can produce scientific notation
-- (e.g. 1e-08). Wrap in printf('%.20f') + rtrim to produce the decimal
-- text format that Decimal::from_str expects.
INSERT INTO snapshot_positions (
    snapshot_id, asset_id, quantity, average_cost, total_cost_basis,
    currency, inception_date, is_alternative, contract_multiplier,
    created_at, last_updated
)
SELECT
    hs.id,
    json_extract(pos.value, '$.assetId'),
    rtrim(rtrim(printf('%.20f', json_extract(pos.value, '$.quantity')), '0'), '.'),
    rtrim(rtrim(printf('%.20f', json_extract(pos.value, '$.averageCost')), '0'), '.'),
    rtrim(rtrim(printf('%.20f', json_extract(pos.value, '$.totalCostBasis')), '0'), '.'),
    json_extract(pos.value, '$.currency'),
    COALESCE(json_extract(pos.value, '$.inceptionDate'), '1970-01-01T00:00:00Z'),
    COALESCE(json_extract(pos.value, '$.isAlternative'), 0),
    rtrim(rtrim(printf('%.20f', COALESCE(json_extract(pos.value, '$.contractMultiplier'), 1)), '0'), '.'),
    COALESCE(json_extract(pos.value, '$.createdAt'), '1970-01-01T00:00:00Z'),
    COALESCE(json_extract(pos.value, '$.lastUpdated'), '1970-01-01T00:00:00Z')
FROM holdings_snapshots hs,
     json_each(hs.positions) pos
WHERE hs.positions IS NOT NULL
  AND hs.positions != '{}'
  AND hs.positions != ''
  AND json_extract(pos.value, '$.assetId') IS NOT NULL;

-- Clear positions JSON after backfill to match the new write-path
-- behavior where positions are always written as '{}'.
UPDATE holdings_snapshots SET positions = '{}' WHERE positions != '{}';
